# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbac815ba18e9834e18632a08f87ecba3193e5b2a3f1ac41c1ba51cefade9b5f78b4422dc7ae01bc363795e3c3657d7941d1ca295ea65451b07e4b6086a7db4d

test:
  secret_key_base: 631cb8580b48d72eef3bd9c3f8d5b45fba038a2bb033323f40d424700e275f6600c325c60e6fd88c28535505694d391cd854c152d36850869a5f52fe8d20c939

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
